services:
  hexlabels:
    image: localhost/hexlables
    container_name: hexlabels
    ports:
      - "8080:8080" # HTTP
      - "8081:8081" # HTTPS
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNET_ENV}
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=${ASPNET_CERT_PASSWORD}
    volumes:
      - ~/.aspnet/https:/https:z
    restart: unless-stopped
  postgres:
    image: postgres:18.4
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: toor321
      POSTGRES_DB: hexlables
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/18/data
  pgadmin:
    image: dpage/pgadmin4:8.4
    container_name: pgadmin_ui
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: toor321
    ports:
      - "8080:80"
    depends_on:
      - postgres
volumes:
  postgres_data:
